version: 2.1
orbs:
  ruby: circleci/ruby@1.0.4
  coveralls: coveralls/coveralls@1.0.6
jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.2-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run tests
          command: bundle exec rspec
 
workflows:
  version: 2
  deploy:
    jobs:
      - test